import pandas as pd
import numpy as np
import time
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
from scipy.optimize import minimize
from .returns_core import calculate_returns, calculate_wealth_index
from .summary_core import describe_returns

def optimize_allocation_for_target_return(target_return, stock_list, date_start='2020-01-01', date_end=None):
    """ Returns the optimal allocation for a given target return"""
    start_time = time.perf_counter()
    df = get_price_data(stock_list, date_start=date_start, date_end=date_end)
    temp_er = calculate_returns(df).dropna()
    er = describe_returns(temp_er)['AnnualizedReturns']

    if target_return > er.max() or target_return < er.min():
        print(f"ERROR: Target return {target_return} must be between {er.min():.4f} and {er.max():.4f}")
        return None, None

    cov = temp_er.cov()

    # Keep output aligned to the requested ticker order.
    asset_order = [ticker for ticker in stock_list if ticker in er.index]
    
    er = er.reindex(asset_order)
    cov = cov.reindex(index=asset_order, columns=asset_order)

    optimal_weights = pd.Series(minimize_vol(target_return, er, cov), index=asset_order, name='weights')
    vol_at_target_return = portfolio_volatility(optimal_weights, cov)
    optimal_weights_table = optimal_weights.to_frame().T
    chart_title = (
        f"Efficient Frontier | Assets: {', '.join(asset_order)} | "
        f"Target Return: {target_return:.4f} | Min Volatility: {vol_at_target_return:.4f}"
    )
    fig = plot_ef(
        100,
        er,
        cov,
        target_return=target_return,
        optimal_vol=vol_at_target_return,
        optimal_weights_series=optimal_weights,
        df_prices=df,
        title=chart_title,
    )
    
    elapsed_seconds = time.perf_counter() - start_time

    # Add footnote with generation time
    fig.text(
        0.5, -0.02,
        f"Generated by QuantFlow, in {elapsed_seconds:.3f}s",
        ha='center', fontsize=9, fontstyle='italic', color='gray',
    )

    # Display and close figure to free memory
    displayed = False
    try:
        from IPython import get_ipython
        if get_ipython() is not None:
            from IPython.display import display
            display(fig)
            displayed = True
    except Exception:
        pass

    if not displayed and 'agg' not in plt.get_backend().lower():
        plt.show()

    plt.close(fig)

    # print(f"Total analysis time: {elapsed_seconds:.3f} seconds\n\n")
    # print(round(optimal_weights_table, 4))
    # print(f"\nVolatility at target return {target_return:.4f} is {vol_at_target_return:.4f}")
    return optimal_weights_table, vol_at_target_return

def get_price_data(stock_list: list[str], source: str = 'yfinance', date_start: str = '2020-01-01', date_end: str = None) -> pd.DataFrame:
    """ Returns a DataFrame of price data for the given stock list"""
    if source == 'yfinance':
        import yfinance as yf
        data = yf.download(stock_list, start=date_start, end=date_end, progress=False)['Close']
        return data
    else:
        raise ValueError(f"Data source '{source}' is not supported.")

def portfolio_returns(weights, returns): 
    """ Weights -> Returns"""
    return weights.T @ returns

def portfolio_volatility(weights, covmat): 
    """ Weights -> Vol"""
    return (weights.T @ covmat @ weights)**0.5

def optimal_weights(n_points, er, cov): 
    """
    generates list of weights to run the optimizer on to minimize the vol
    """
    target_rs = np.linspace(er.min(), er.max(), n_points)
    asset_index = er.index if isinstance(er, pd.Series) else pd.RangeIndex(len(er))
    weights = [
        pd.Series(minimize_vol(target_return, er, cov), index=asset_index, name=target_return)
        for target_return in target_rs
    ]
    return weights

def plot_ef(n_points, er, cov, target_return=None, optimal_vol=None, optimal_weights_series=None, df_prices=None, title=None):
    """ Plots the multi-asset efficient frontier with normalized returns and allocation """
    
    # Contrasting pastel palette
    pastel_colors = [
        '#FF6B6B', '#4ECDC4', '#45B7D1', '#96CEB4',
        '#FFEAA7', '#DDA0DD', '#98D8C8', '#F7DC6F',
    ]

    weights = optimal_weights(n_points, er, cov)

    rets = [portfolio_returns(w, er) for w in weights]
    vols = [portfolio_volatility(w, cov) for w in weights]
    ef = pd.DataFrame({'Returns': rets, 'Volatility': vols})

    # Layout: allocation table on top (10% height), two charts below (90% height)
    fig = plt.figure(figsize=(14, 8), constrained_layout=True)
    gs = fig.add_gridspec(2, 2, height_ratios=[1, 9])

    # --- Top row: Allocation Table (spans full width) ---
    ax_table = fig.add_subplot(gs[0, :])
    ax_table.axis('off')
    if optimal_weights_series is not None:
        allocation_data = optimal_weights_series.to_frame('Allocation %').T * 100
        allocation_data = allocation_data.round(2)

        col_labels = list(allocation_data.columns)
        cell_values = [[f"{allocation_data[col].values[0]:.2f}%" for col in col_labels]]

        table = ax_table.table(
            cellText=cell_values,
            colLabels=col_labels,
            cellLoc='center',
            loc='center',
            colWidths=[0.12] * len(col_labels),
        )
        table.auto_set_font_size(False)
        table.set_fontsize(11)
        table.scale(1, 1.8)

        for j in range(len(col_labels)):
            table[(0, j)].set_facecolor('#40466e')
            table[(0, j)].set_text_props(weight='bold', color='white')
            table[(1, j)].set_facecolor('#f0f0f0')

        ax_table.set_title('Portfolio Allocation', fontsize=12, fontweight='bold', pad=10)

    # --- Bottom-left: Efficient Frontier ---
    ax1 = fig.add_subplot(gs[1, 0])
    ax1.plot(ef['Volatility'], ef['Returns'], color=pastel_colors[0], linewidth=2)

    if target_return is not None and optimal_vol is not None:
        ax1.scatter(
            [optimal_vol],
            [target_return],
            color=pastel_colors[1],
            edgecolors='black',
            s=150,
            label=f'Optimal Allocation at {target_return}% Portfolio Return',
            zorder=3,
        )
        ax1.legend()

    ax1.set_title('Efficient Frontier', fontsize=12, fontweight='bold')
    ax1.set_xlabel('Volatility')
    ax1.set_ylabel('Returns')
    ax1.grid(True, alpha=0.3)

    # --- Bottom-right: Wealth Index ($1 start) ---
    ax2 = fig.add_subplot(gs[1, 1])
    if df_prices is not None:
        returns_df = calculate_returns(df_prices).dropna()
        wealth_df = calculate_wealth_index(returns_df, start=1.0)
        wealth_cols = [c for c in wealth_df.columns if c.startswith('_q_') and c.endswith('_wealth_index')]
        for i, col in enumerate(wealth_cols):
            label = col.replace('_q_', '').replace('_wealth_index', '')
            ax2.plot(
                wealth_df.index, wealth_df[col],
                label=label,
                color=pastel_colors[i % len(pastel_colors)],
                linewidth=2,
            )

        ax2.set_title('Wealth Index ($1 Investment)', fontsize=12, fontweight='bold')
        ax2.set_xlabel('Date')
        ax2.set_ylabel('Value ($)')
        ax2.legend(loc='best', fontsize=9)
        ax2.grid(True, alpha=0.3)

    if title:
        fig.suptitle(title, fontsize=13, fontweight='bold')

    return fig

def minimize_vol(target_return, er, cov):
    """
    target_return -> W
    """
    n = er.shape[0] # number of assets
    
    #Optimizers need: objective function, contstraints, initial guess
    
    # Initial Guess is just equally divided among the assets
    init_guess = np.repeat(1/n, n)
    
    # constraints - 
    
    # contraints # 1: all weights have to be between 0 and 1.  Less than 0, this is shorting, and over 1 this is leverage
    bounds = ((0.0, 1.0),)*n # tuple of min 0 and max 1 (0.0,1.0), repeated n times for all the assets (weights)
    # ((0.0,1.0),)*5 will return (0.0, 1.0), (0.0, 1.0), (0.0, 1.0), (0.0, 1.0), (0.0, 1.0)
    
    # contraints # 2: 
    # whatever weights
    return_is_target = {
        'type': 'eq'
        , 'args': (er,)
        , 'fun': lambda weights, er: target_return - portfolio_returns(weights, er)
    }
    
    # contraint # 3: 
    # weights sum to 1
    weights_sum_to_1= {
        'type': 'eq'
        , 'fun': lambda weights: np.sum(weights)-1
    }
    results = minimize(
        portfolio_volatility, init_guess, 
        args=(cov, ), method="SLSQP", 
        options = {'disp': False},
        constraints=(return_is_target, weights_sum_to_1), 
        bounds=bounds
    )
    
    return results.x